### ISSUE TITLE
Old Steam Cafe Titles Still Showing after re-exporting

### ISSUE THREAD

**Issue by vrarrival** [leckylao/SpringboardVR-Games-Export-System#2]
Hi Lecky,
I hope you guys will be opening up again soon if you haven't already done so? We were allowed to open up last weekend here in Perth - fairly steady during the weekend which is encouraging!
Quick one regarding the SpringboardVR Games Export System. When I re-export out the titles that are in my SpringboardVR library, it also includes some of the old Steam Cafe games that I no longer use and are not in the SpringboardVR title list anymore - example in the word doc pictures below is Ocean Rift, Serious Sam and Aeon. Is there a way to clear the Steam Cafe games that are no longer being used. I am happy to pay you to look into this as you have provided a great add-on here!
[Doc1.docx](https://github.com/leckylao/SpringboardVR-Games-Export-System/files/4756815/Doc1.docx)

**Comment by leckylao** [comment]
Sorry just saw the message. Will have a look.

**Comment by leckylao** [comment]
Hi @vrarrival 

Thank you for trying out our system. I’ve had a look at the issue but can’t find what’s causing it as those games were returned from SpringboardVR with 8 stations installed, so it should show on your library page as well. But I have added a new data field to store more data to see if any other fields can use to filter those out. The new update also fixed to show the tags correctly and will roll out tonight. So please try to run export again. 

FYI What I do usually is just disable the game instead of deleting it, which would also hide it from the games page. 
![image](https://user-images.githubusercontent.com/148800/85294509-12d85f00-b4e2-11ea-8f98-2ebe9019893f.png)

**Comment by leckylao** [comment]
@vrarrival new version has been rolled out for this fix, feel free to reimport and try again.
